Milestone 1: Adding contents and styles to my portfolio page
bushmusi/Microverse-Portfolio pull request #1
Opened 2022-01-08 13:45 UTC by bushmusi

# Linters milestone 1:: Add contents and styles to my portfolio page

***In this milestone 1:***
    1. I have added linters and .gitignore file
    2. Detail description in README.md file
    3. Flexbox styles has been added for page responsive

2022-01-08 16:01 UTC, Whoistolu requested changes
Hi @bushmusi ,

Good job so far however, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

### To highlight
✔️ Proper Commit Messages
✔️ Descriptive Pull Request

- [ ] [OPTIONAL] Kindly fix the link to your screenshot in the README file as it is currently broken.

_Check the inline comments under the review for sections to improve._

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-01-08 16:01 UTC, Whoistolu commented on index.html
> +</html>
- [ ] [REQUIRED] Kindly ensure that you stick to the provided [Figma Template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A10) as much as possible (Margins, font, font sizes, image). 
   - Kindly add the hamburger icon to your nav and ensure it has a `nav` tag
    - Please add the proper margin-top to your logo and ensure it has a link `a` tag
  
### Your design
![your-design](https://user-images.githubusercontent.com/58692590/148651107-fd527cc6-af99-41d7-9971-5f75e597aa46.png)

### Figma Template
![figma](https://user-images.githubusercontent.com/58692590/148651115-a48fbd69-45c6-46da-920d-4cae38e92676.png)

2022-01-08 16:01 UTC, Whoistolu commented on index.html
> +        </div>
- [ ] [REQUIRED] This should be wrapped in an `h1` tag for proper semantics purposes.

2022-01-08 16:01 UTC, Whoistolu commented on index.html
> +        </div>
- [ ] [REQUIRED] This should use a header tag `h2` for standard semantic purposes.

2022-01-08 16:01 UTC, Whoistolu commented on index.html
> +    </div>
- [ ] [REQUIRED] The list of icons uses a `ul` tag to group them, and `li` per icon; each icon has a link ` a` tag. Please implement this also for proper semantic standards.
- [ ] [REQUIRED]  Please ensure you implement the proper margins as applied in the [figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A10).

2022-01-13 07:15 UTC, brytebee requested changes
Hi, @ 👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- Proper GitHub flow✔️
- clean code✔️
- good UI design✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-13 07:15 UTC, brytebee commented on index.html
> +    </nav>
- [ ] **Required:** The container of this `nav` should be a `header`. This is for implementing [HTML semantic](https://developer.mozilla.org/en-US/docs/Glossary/Semantics#semantics_in_html) tag which is good for page indexing and SEO.

2022-01-13 07:15 UTC, brytebee commented on index.html
> +    </div>
- [ ] **Required:** To also implement [HTML semantic](https://developer.mozilla.org/en-US/docs/Glossary/Semantics#semantics_in_html) tags stated previously, consider using `section` rather than `div` to place your _headline._ What do you think? 😄 
- [ ] **Optional:** Moreso, it would make some _semantic_ sense to replace most of the `div`s in your website with appropriate semantic tags. Think about it... 🤔

2022-01-13 07:15 UTC, brytebee commented on index.html
> +            </div>
- [ ] **Required:** In these above sections, you are making a list of items, it is more _semantic_ to use [`ul` and `li`](https://stackoverflow.com/questions/13416866/why-should-i-use-ul-li-in-my-html) tags for this purpose as you have rightly done in the preceding section 👇. Try it out!

2022-01-13 14:30 UTC, bushmusi commented
_hi_  @brytebee
**Your review is so clear and helpful full Thanks 🙇‍♂️**

2022-01-13 18:43 UTC, Lordkaito approved these changes
Hi @bushmusi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-13 19:24 UTC, bushmusi commented
> Hi @bushmusi,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

I am happy to hear that 🥂.

2022-01-13 19:25 UTC, merged